### ISSUE TITLE
Well_connected_components: Mistake in dergee second moment metric

### ISSUE THREAD

**Issue by bartoszbryg** [Bears-R-Us/arkouda-njit#142]
Degree second moment should be calculated by dividing the sum of the degrees squared by the number of nodes (source: Albert-László Barabási - Network Science - Chapter 4 (http://networksciencebook.com/)). The exact explanation can be found on StackOverflow (https://stackoverflow.com/questions/64803756/python-how-to-get-second-moment-of-degree-distribution-by-networkx).

In line 1378 in wellConnectedComponents, the second moment is not divided by the number of nodes so as in the rest of the file. The solution to the problem is to edit the line from `stats.degree_second_moment = second_moment;` to `stats.degree_second_moment = second_moment / stats.n_vertices;`

**Comment by mdindoost** [comment]
Thank you. we will work on it.

**Comment by mdindoost** [comment]
degree_second_moment issue fixed. Thanks again
