### ISSUE TITLE
Issues with global clustering coef / global transitivity / triangle density

### ISSUE THREAD

**Issue by bartoszbryg** [Bears-R-Us/arkouda-njit#143]
**1.** The global clustering coefficient is the total number of triangles in the whole network * 3 divided by the total number of wedges in the whole network. Since the global clustering coefficient refers only to one cluster, I suggest changing the name from global clustering coefficient to clustering coefficient for cluster metrics! **(line 3019)**

**2.** Global transitivity and global clustering coefficients and transitivity and clustering coefficients are the same concepts and produce the same values. I suggest removing one of them (e.g. global transitivity). (Line 3031).

**3.** Triangle density for connected clusters is the same as the clustering coefficient and transitivity. Moreover, as I can see in line 820 `updatedMetrics.triangleDensity = if edges > 0 
                                   then finalTriangles:real / edges:real
                                   else 0.0;`, triangle density is incorrectly calculated (correct version -> `traingleDensity = (nr of triangles for cluster * 3) / nr of wedges in the same cluster`). I suggest removing the triangle density or changing its formula to the correct form.

**Citation:** 
"Definition 1 (triangle-dense graph). The triangle density of an undirected
graph G = (V, E) is τ (G) := 3t(G)/w(G), where t(G) is the number of triangles
in G and w(G) is the number of wedges in G (conventionally, τ (G) = 0 if w(G) = 0).
The class of -triangle-dense graphs consists of the graphs G with τ (G) ≥ .
Since every triangle of a graph contains three wedges, and no two triangles share
a wedge, the triangle density of a graph is between 0 and 1. In the social sciences,
triangle density is usually called the transitivity of a graph [WF94] and also the (global)
clustering coefficient. We use the term triangle density because “transitivity” already
has strong connotations in graph theory."

**Sources:**
**[1]** Gupta, Rishi, et al. “Decompositions of Triangle-Dense Graphs.” SIAM Journal on Computing, vol. 45, no. 2, Jan. 2016, pp. 197–215, www.timroughgarden.org/papers/triangle.pdf, https://doi.org/10.1137/14095533. Accessed 17 Dec. 2024. **(page 2)**
**[2]** Kong, Xiangjie, et al. “Academic Social Networks: Modeling, Analysis, Mining and Applications.” Journal of Network and Computer Applications, vol. 132, Apr. 2019, pp. 86–103, https://doi.org/10.1016/j.jnca.2019.01.029. **(section 4.1.4)**
**[3]** Newman, M. E. J. “The Structure and Function of Complex Networks.” SIAM Review, vol. 45, no. 2, Jan. 2003, pp. 167–256, https://doi.org/10.1137/s003614450342480. **(section III B)**

**Comment by mdindoost** [comment]
Thanks will work on it.

**Comment by mdindoost** [comment]
Issue 1 // Fixed 
Issue 2 -- needs more investigation. 
Issue 3 // Triangle density  redefined as triangles per vertex in cluster
