### ISSUE TITLE
Triangle counting returns node ID rather than triangle count

### ISSUE THREAD

**Issue by jakobtroidl** [Bears-R-Us/arkouda-njit#34]
For some reason, the triangle counting function in Arachne returns the node input ID rather than the found triangles. Here's the head .csv dataset I used to build the graph. 

```csv
**HEADER**
int64,int64,float64
*/HEADER/*
bodyId_pre,bodyId_post,weight
294437328,295470623,1
294437328,295133902,1
294437328,448260940,1
294437328,294783423,1
294437328,5812979995,1
294437328,295474441,2
294437328,265120223,1
294437328,296139882,1
```

Here's the code snippet and output of my triangle function call. 
```python
tri_nodes = ak.array([-1])
count = ar.triangles(graph, vertexArray=tri_nodes)
print(count)
# [-1]
```

@alvaradoo thinks this might be a bug. Any idea how this could be fixed?

**Comment by alvaradoo** [comment]
@jakobtroidl Better late than never right? This issue should be fixed with the refactoring that was just merged in for triangle counting.

**Comment by jakobtroidl** [comment]
Amazing, thanks @alvaradoo!
