### ISSUE TITLE
Running list of Arachne errors that kill the Arkouda server

### ISSUE THREAD

**Issue by alvaradoo** [Bears-R-Us/arkouda-njit#38]
Currently, errors in Arachne such as using uint64 instead of int64 during file ready are crashing the server. These errors should be handled properly so that the Arkouda server doesn't need to be restarted every time an error is encountered. Most of this will be handled by using Chapel throws and catches. (https://chapel-lang.org/docs/language/spec/error-handling.html). The reading method is just an example, all functions will need to be checked .

**Comment by ak47mrj** [comment]
assigned

**Comment by alvaradoo** [comment]
We will use this to document any errors that we run into with Arachne that kills the server. **The comments in here should be documented in their own separate issue and that issue should be linked in here.**
