### ISSUE TITLE
Indexing into returned arrays from graph methods only works with internal vertex values

### ISSUE THREAD

**Issue by alvaradoo** [Bears-R-Us/arkouda-njit#40]
Say we have a graph, `G` with vertex names {2,6,7} the internal values would be represented with {0,1,2}. When we run BFS on `G` the returned depth array, `D`, is based off values {0,1,2}. How can we let the user index into `D` based off the original values instead of the internal values?

**Comment by alvaradoo** [comment]
Yes, but the issue is doing this in a way that remains natural for the user. We can return two arrays instead of one to hold the original vertex values but that would require the user to do an indexing that looks like `depth[vertex_map[u]]` where `u` is the original vertex name. 

I am thinking something more along the lines of a class that inherits from `pdarray` called `apdarray` (associative pdarray) that behaves like a `pdarray` but performs the internal indexing as `depth[vertex_map[u]]` and overrides indexing so that the user can just do `depth[u]`instead of having to remember to always call the `vertex_map`.

**Comment by zhihuidu** [comment]
Yes, the apdarray will be easy and natural for users. I am thinking if we need to include such a mapping mechanism into our graph data structure.

**Comment by alvaradoo** [comment]
I think the best solution to this would be that for any kernel that returns some type of value specified for each node or edge we should return a tuple `(nodes, values)` or `(edges, values)` respectively. This will mean we don't have to generate a new class for arrays returned by Arachne and it falls in line with some Arkouda methods that return tuples in a similar manner. @mostroski @zhihuidu Thoughts on this? Small example of how it would work:

```Python
import arachne as ar

src = ak.array([0,1,2,3,4,5,6,7,8])
dst = ak.array([1,2,3,4,5,6,7,8,9])
graph = ar.Graph()
graph.add_edges_from(src,dst)

(nodes, layers) = ar.bfs_layers(graph)
print(f"Node {nodes[1]} has layer {layer[1]}")

```

If I'm not wrong, those arrays could then be easily transferred to other Arkouda functions that performs groupings on `layers` or some type of indexing that can also be used on `nodes`.

**Comment by alvaradoo** [comment]
The user will be expected to know that if an array of size `m` or `n` is returned, then those values will refer to the sorted lists of `graph.edges()` and `graph.nodes()`.
