### ISSUE TITLE
Port arkouda-contrib/akgraph graph generators to arachne

### ISSUE THREAD

**Issue by alvaradoo** [Bears-R-Us/arkouda-njit#90]
There are some graph generators in [arkouda-contrib/akgraph](https://github.com/Bears-R-Us/arkouda-contrib/blob/main/akgraph/client/akgraph/generators.py) that can be ported into Arachne. They are expected to live inside of [arachne/client](https://github.com/Bears-R-Us/arkouda-njit/tree/main/arachne/client/arachne) in a file called `generators.py` or similar. 

Most of the return statements for the generator functions are of the format:
```python
return standardize_edges(U,V)
```` 

This can be directly mapped to Arachne functionality by doing:
```python
graph = ar.Graph() # or DiGraph() or PropGraph()
graph.add_edges_from(U,V)
```

Users should be able to dictate if they want to build a Graph(), DiGraph(), or PropGraph(). No need to worry about remove multiple edges or self-loops as the `add_edges_from()` method handles removing multiple edges, and self-loops are allowed in the base data structure.

**Comment by larjarj31** [comment]
Summary of changes:
(Ported Functionality from akgraph.generators located in arkouda-contrib)
newly created module generators.py in (/arachne/client) supports the following methods which graph creation, for the following graph types: complete graph, karate_club graph, random tree graphs, RMAT graphs, path graphs and the watts_strogatz_graph. User can specify which arachne graph type they want (ie ar.Graph, ar.Digraph, ar.PropGraph)

Tests:
for random graph types: /test/random_generators.py
for deterministic graph types: /test/detereministic_generators.py

**Comment by larjarj31** [comment]
Summary of changes:
(Ported Functionality from akgraph.generators located in arkouda-contrib)
newly created module generators.py in (/arachne/client) supports the following methods which graph creation, for the following graph types: complete graph, karate_club graph, random tree graphs, RMAT graphs, path graphs and the watts_strogatz_graph. User can specify which arachne graph type they want (ie ar.Graph, ar.Digraph, ar.PropGraph)

Tests:
for random graph types: /test/random_generators.py
for deterministic graph types: /test/detereministic_generators.py
