### ISSUE TITLE
read_matrix_market_file() bug (relating to reading in karate club digraph)

### ISSUE THREAD

**Issue by arjreddy97** [Bears-R-Us/arkouda-njit#95]
There seems to be an issue relating to the way way read_matrix_market_file() reads in the karate.mtx file ( in /arachne/data/)  and instantiates an ar.Digraph. The edges added in don't appear to be correct.

**Comment by alvaradoo** [comment]
This was caused due to an issue with the edge aggregators in the Chapel method `readMatrixMarketFileMsg`. The aggregators were removed in favor of:

```
src[ind] = temp[0]:int;
dst[ind] = temp[1]:int;
wgt[ind] = temp[2]:real;
```
